### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by MarcoPNS** [networkteam/Networkteam.Neos.PasswordReset#16]
I would like to use that package with the newest Neos version. I need to use "dev-master" at the moment because 1.2.0 does not work with the newest neos version. this fix is missing: https://github.com/networkteam/Networkteam.Neos.PasswordReset/pull/15

would be happy if you publish a new version.

**Comment by networkteamcom** [comment]
Hi @MarcoPNS,

I have created the [2.0.0](https://github.com/networkteam/Networkteam.Neos.PasswordReset/releases/tag/2.0.0) tag from master.
